<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150928235721 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE grandhotel_hausnetz_domain_model_event");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE grandhotel_hausnetz_domain_model_event (persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, changeuser VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, container VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, createuser VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, title VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, referenceid INT DEFAULT NULL, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, startdate DATETIME DEFAULT NULL, enddate DATETIME DEFAULT NULL, location VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, wholeday TINYINT(1) DEFAULT NULL, active TINYINT(1) DEFAULT NULL, changedate DATETIME DEFAULT NULL, createdate DATETIME DEFAULT NULL, deleted TINYINT(1) DEFAULT NULL, recurringstartdate DATETIME DEFAULT NULL, recurringenddate DATETIME DEFAULT NULL, INDEX IDX_938BCBC6C7A2EC1B (container), INDEX IDX_938BCBC611DDADAE (changeuser), INDEX IDX_938BCBC6DF736B67 (createuser), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE grandhotel_hausnetz_domain_model_event ADD CONSTRAINT FK_938BCBC611DDADAE FOREIGN KEY (changeuser) REFERENCES grandhotel_hausnetz_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE grandhotel_hausnetz_domain_model_event ADD CONSTRAINT FK_938BCBC6C7A2EC1B FOREIGN KEY (container) REFERENCES grandhotel_hausnetz_domain_model_container (persistence_object_identifier)");
		$this->addSql("ALTER TABLE grandhotel_hausnetz_domain_model_event ADD CONSTRAINT FK_938BCBC6DF736B67 FOREIGN KEY (createuser) REFERENCES grandhotel_hausnetz_domain_model_user (persistence_object_identifier)");
	}
}