<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150925114137 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE typo3_flow3_resource_resource DROP FOREIGN KEY typo3_flow3_resource_resource_ibfk_1");
		$this->addSql("CREATE TABLE grandhotel_hausnetz_domain_model_container (persistence_object_identifier VARCHAR(40) NOT NULL, changeuser VARCHAR(40) DEFAULT NULL, createuser VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, color VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, referenceid INT DEFAULT NULL, active TINYINT(1) DEFAULT NULL, changedate DATETIME DEFAULT NULL, createdate DATETIME DEFAULT NULL, deleted TINYINT(1) DEFAULT NULL, INDEX IDX_E4AB7B3711DDADAE (changeuser), INDEX IDX_E4AB7B37DF736B67 (createuser), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE grandhotel_hausnetz_domain_model_container ADD CONSTRAINT FK_E4AB7B3711DDADAE FOREIGN KEY (changeuser) REFERENCES grandhotel_hausnetz_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE grandhotel_hausnetz_domain_model_container ADD CONSTRAINT FK_E4AB7B37DF736B67 FOREIGN KEY (createuser) REFERENCES grandhotel_hausnetz_domain_model_user (persistence_object_identifier)");
		$this->addSql("DROP TABLE typo3_flow3_mvc_web_routing_objectpathmapping");
		$this->addSql("DROP TABLE typo3_flow3_resource_resource");
		$this->addSql("DROP TABLE typo3_flow3_resource_resourcepointer");
		$this->addSql("DROP TABLE typo3_flow3_security_account");
		$this->addSql("DROP TABLE typo3_flow3_security_authorization_resource_securitypublis_6180a");
		$this->addSql("DROP TABLE typo3_flow3_security_policy_role");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE typo3_flow3_mvc_web_routing_objectpathmapping (objecttype VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, uripattern VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, pathsegment VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, identifier VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(objecttype, uripattern, pathsegment)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_flow3_resource_resource (flow3_persistence_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, resourcepointer VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, filename VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, fileextension VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, INDEX IDX_B4D45B323CB65D1 (resourcepointer), PRIMARY KEY(flow3_persistence_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_flow3_resource_resourcepointer (hash VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(hash)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_flow3_security_account (flow3_persistence_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, party VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, accountidentifier VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, authenticationprovidername VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, credentialssource VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, creationdate DATETIME DEFAULT NULL, expirationdate DATETIME DEFAULT NULL, roles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT '(DC2Type:array)', INDEX IDX_44D0753B38110E12 (party), PRIMARY KEY(flow3_persistence_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_flow3_security_authorization_resource_securitypublis_6180a (flow3_persistence_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, allowedroles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT '(DC2Type:array)', PRIMARY KEY(flow3_persistence_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_flow3_security_policy_role (identifier VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE typo3_flow3_resource_resource ADD CONSTRAINT typo3_flow3_resource_resource_ibfk_1 FOREIGN KEY (resourcepointer) REFERENCES typo3_flow3_resource_resourcepointer (hash)");
		$this->addSql("DROP TABLE grandhotel_hausnetz_domain_model_container");
	}
}