-
  name: 'Default'
  uriPattern: '{@controller}/{@action}'
  defaults:
    '@package':    'Grandhotel.Hausnetz'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'


-
  name: 'Home'
  uriPattern: ''
  defaults:
    '@package':    'Grandhotel.Hausnetz'
    '@controller': 'Announcements'
    '@action':     'index'
    '@format':     'html'