#                                                                        #
# Default routes configuration for the Welcome package                   #
#                                                                        #

-
  name: 'Welcome screen'
  uriPattern: 'flow/welcome'
  defaults:
    '@package':    'TYPO3.Welcome'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'

-
  name: 'Redirect to welcome screen'
  uriPattern: ''
  defaults:
    '@package':    'TYPO3.Welcome'
    '@controller': 'Standard'
    '@action':     'redirect'
    '@format':     'html'
